---
title: "Svect: Fast Vectorial Alignments"
author:
- name: Roberto Raitz
  affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
   - Federal University of Paraná, Department of Biochemistry and Molecular Biology, Curitiba, Paraná, Brazil.
   - Federal University of Paraná, Department of Genetics, Curitiba, Paraná, Brazil.
- name: Mariane Gonçalves Kulik 
  affiliation: Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
-  name: Ricardo Voyceik 
   affiliation: Federal University of Minas Gerais, Institute of Biological Sciences (ICB), Belo Horizonte, Minas Gerais, Brazil.
-  name: Letícia Graziela Costa Santos de Mattos 
   affiliation: Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.  
-  name: Josué Oliveira Camargo 
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
   - Federal University of Paraná, Department of Biochemistry and Molecular Biology, Curitiba, Paraná, Brazil.
-  name: Aryel Marlus Repula de Oliveira
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil. 
   - Federal University of Paraná, Department of Genetics, Curitiba, Paraná, Brazil.
-  name: Bruno Thiago de Lima Nichio
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
   - Federal University of Paraná, Department of Biochemistry and Molecular Biology, Curitiba, Paraná, Brazil.
-  name: Jeroniza Nunes Marchaukoski
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
-  name: Antonio Camilo da Silva Filho
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
   - Federal University of Paraná, Department of Pharmaceutical Sciences, Curitiba, Paraná, Brazil.
-  name: Dieval Guizelini
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
-  name: José Miguel Ortega
   affiliation: 
   - Federal University of Minas Gerais, Institute of Biological Sciences (ICB), Belo Horizonte, Minas Gerais, Brazil.
-  name: Fabio de Oliveira Pedrosa
   affiliation: 
   - Federal University of Paraná, Graduate Program in Bioinformatics, Curitiba, Paraná, Brazil.
   - Federal University of Paraná, Department of Biochemistry and Molecular Biology, Curitiba, Paraná, Brazil.  
- name: Danrley Rafael Fernandes
  affiliation: Federal University of Paraná, Graduate in Biological Sciences, Curitiba, Paraná, Brazil.
output:
  BiocStyle::html_document
package: SVect
abstract: |
 This package possibilite the use of SWeep method in R. This method provides a powerful tool to alignment free DNA analysis.
vignette: >
  %\VignetteIndexEntry{Svect}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# What is this?
This is a package with a couple of functions to possibilite the use of the SWeep method in R

## What is SweeP?
The “Spaced Words Projection (SWeeP)” is a method for representing biological sequences using relatively, it uses the spacedwords concept by scanning sequences and generating indices to create a higherdimensional vector that is later projected into a smaller randomly oriented orthonormal base. This function is suitable for making high quality comparisons between sequences allowing analyzes that are not possible due to the computational limitation of the traditional techniques. The method is available at [SWeeP](https://sourceforge.net/projects/spacedwordsprojection/) (PIERRI, 2019). 

## How fast is this method?
The main speed gain in this method is the constanci in the processing time. The response time grows linear to the number of inputs, while in other methods that grow is exponencial

# What is in?
Two functions orthbase, that generates an orthonormal matrix of a chosen size, and SWeeP, a function that applies the SWeeP method

# How to use?
```{r}
library(SVect)
baseMatrix <- orthbase(160000,10)
data(datastring)
cat(datastring, file = "exdna.fas", sep = "\n")
return <- SWeeP("exdna.fas",baseMatrix)
distancia <- dist(return, method = "euclidean")
tree <- hclust(distancia, method="ward.D")
plot(tree, hang = -1, cex = 1)
```

# References
- Pierri,C. R. *et al*. **SWeeP: Representing large biological sequences data sets in compact vectors**. (2019). 
  
